### ISSUE TITLE
socket_sendto errors need to be silenced

### ISSUE THREAD

**Issue by Jalle19** [TomNomNom/phpwol#1]
Refernce: https://github.com/TomNomNom/phpwol/blob/master/Phpwol/Socket.php#L9

If you attempt to send a packet to a broadcast address that is different from the hosts broadcast address (e.g. attempting to send to `255.255.0.0` from a machine that is on `255.255.255.0`) PHP will die with an error like "socket_sendto(): unable to write to socket [101]: Network is unreachable". This error should be caught so the method can return false on any error.

**Comment by TomNomNom** [comment]
Good catch, thanks!

Ideally I'd rather add a check for that particular case, but having given it some thought I think it would actually be pretty difficult to reliably get the correct subnet mask (especially on machines with multiple interfaces on different networks).

As you've suggested, silencing the error might actually be the best way to go :(

**Comment by TomNomNom** [comment]
Fixed in 9126f22d57e4403e0569b1b5e9c91c697a394260 :)

Let me know if you have any more problems.

**Comment by Jalle19** [comment]
Holy shit, thanks! Open source at its best!

> Ideally I'd rather add a check for that particular case, but having given it some thought I think it would actually be pretty difficult to reliably get the correct subnet mask (especially on machines with multiple interfaces on different networks).

I came to the same conclusion, most applications I've seen that try to figure out your network address end up getting it wrong when there are more interfaces than one.

**Comment by TomNomNom** [comment]
Hah; you're welcome :)
