### ISSUE TITLE
Sending Magic Packet to Broadcast

### ISSUE THREAD

**Issue by strebl** [tomnomnom/phpwol#2]
Hi @tomnomnom 

Thanks for your work, like your package so far 👍 

I have a question about this line: https://github.com/tomnomnom/phpwol/blob/master/Phpwol/Socket.php#L12

What's the reason you're setting the `MSG_DONTROUTE` flag?
That's what preventing me from sending the magic packet to 255.255.255.255. It works after changing the flag to `0`.

Regards

**Comment by tomnomnom** [comment]
Hi @strebl. Thanks for your kind words :)

To be honest, I hadn't considered cross-network WOL. My understanding is that most routers don't support it; but I'm happy for it to be changed :)

Out of interest: why would you want to send a magic packet to `255.255.255.255`? As far as I know that will broadcast only to `0.0.0.0` AKA localhost.

**Comment by strebl** [comment]
I have no idea how many routers support it. But as far as I understand, removing this flag just enables that feature without harming anything, am I right?

Im working in a environment with around 1500 computers which are placed in different networks. `255.255.255.255` is the global broadcast and will reach, if properly configured, all desired networks with just one call to your packet.

**Comment by tomnomnom** [comment]
@strebl I'm pretty sure you're right about removing the flag. 

I may be misremembering, but I think there's a specific exception for `255.255.255.255` that broadcasts only to localhost to stop broadcasts to the entire internet.

Either way, I've made the change in a branch (https://github.com/tomnomnom/phpwol/tree/route) Please let me know if it works :)

**Comment by strebl** [comment]
Sorry @tomnomnom for not talking clearly enough.
Your totally right about the internet. You can't broadcast to the internet. But lets say you have multiple routed private networks: `192.168.1.0`, `192.168.2.0`, `172.20.3.0`, `172.17.3.0`.
Now, if you send a package to `255.255.255.255`, and the router is configured properly, the package reaches all hosts in all your networks.

Another another think I didn't tell you: I forked your project and tested it myself. I really didn't expect such a fast answer 👍
I was ready to create a PR if you would be interested in that change. But you were very fast 😄. 
Because of that I can say your change does work 👍

**Comment by tomnomnom** [comment]
Submit the PR and get your name against it :)
